#!/usr/bin/env python

import os
import sys
import subprocess

http_proxy = 'http://127.0.0.1:3128'
path = '/hackenv/bin:/usr/bin:/bin'
lib = os.path.abspath('lib')

subprocess.call(
    ['nice', '-n10',
     '/usr/bin/umlbox',
     '--no-stdin',
     '--base-mounts',
     '--mount', lib,
     '--translate-write', '/hackenv', os.environ['HACKENV'],
     '--translate', '/hackenv/.hg', os.path.join(os.environ['HACKENV'], '.hg'),
     '--cwd', '/hackenv',
     '--env', 'PATH=' + path,
     '--env', 'HACKENV=/hackenv',
     '--env', 'IRC_NICK=' + os.environ['IRC_NICK'],
     '--env', 'IRC_IDENT=' + os.environ['IRC_IDENT'],
     '--env', 'IRC_HOST=' + os.environ['IRC_HOST'],
     '--env', 'IRC_COMMAND=' + os.environ['IRC_COMMAND'],
     '--env', 'IRC_TARGET=' + os.environ['IRC_TARGET'],
     '--env', 'IRC_MESSAGE=' + os.environ['IRC_MESSAGE'],
     '--env', 'http_proxy=' + http_proxy,
     '--timeout', '30',
     os.path.join(lib, 'limits')] + sys.argv[1:])
