#!/usr/bin/env python3

import os
import sys
import subprocess

http_proxy = 'http://127.0.0.1:3128'
path = '/hackenv/bin:/usr/bin:/bin'

subprocess.run(
    ['nice', '-n10',
     '/usr/bin/umlbox',
     '--no-stdin',
     '--base-mounts',
     '--translate-write', '/hackenv', os.environ['HACKENV'],
     '--translate', '/hackenv/.hg', os.path.join(os.environ['HACKENV'], '.hg'),
     '--cwd', '/hackenv/tmp',
     '--env', 'PATH=' + path,
     '--env', 'HACKENV=/hackenv',
     '--env', 'IRC_NICK=' + os.environ['IRC_NICK'],
     '--env', 'IRC_IDENT=' + os.environ['IRC_IDENT'],
     '--env', 'IRC_HOST=' + os.environ['IRC_HOST'],
     '--env', 'IRC_COMMAND=' + os.environ['IRC_COMMAND'],
     '--env', 'IRC_TARGET=' + os.environ['IRC_TARGET'],
     '--env', 'IRC_MESSAGE=' + os.environ['IRC_MESSAGE'],
     '--env', 'http_proxy=' + http_proxy,
     '--timeout', '30',
     '--limit', 'FSIZE', '10485760',
     '--limit', 'MEMLOCK', '0',
     '--limit', 'NPROC', '128',
     '--'] + sys.argv[1:])
